In [1]:
import numpy as np
# Create a 1D array of numbers 1-10
v = np.array([1,2,3,4,5,6,7,8,10])
print(v)

[ 1  2  3  4  5  6  7  8 10]


In [3]:
import numpy as np
# Create a 3x3 matrix of zeros
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
# Create a 4x4 identity matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
import numpy as np
# Create an array from 0 to 1 with 11 evenly spaced numbers
space = np.linspace(0,1,11) # start, stop, numpoints
print(space)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [8]:
import numpy as np
# Create a 2x3 array of ones with dtype float32
ones = np.ones((2,3), dtype='float32')
print(ones)
print(ones.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float32


In [11]:
# Practicing Essential Properties
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

# .shape - dimensions of the array (MOST IMPORTANT)
print(arr.shape) # (3, 4) - 3 rows, 4 columns

# .ndim - number of dimensions
print(arr.ndim) # 2 (it's a 2D array)

# .size - total number of elements
print(arr.size) # 12( 3*4 = 12 elements)

# .dtype - data type of elements
print(arr.dtype) #float64 by default

# len() - length of first dimension
print(len(arr)) # 3 (number of rows)

(3, 4)
2
12
int64
3


In [2]:
# Understanding shapes
import numpy as np

#1D array
v = np.array([1,2,3])
print(v.shape)

#2D array(matrix)
M = np.array([[1,2,3],
              [4,5,6]])
print(M.shape)

#3D array
T = np.zeros((2,3,4)) # 2 layers of 3x4 matrix
print(T.shape)

(3,)
(2, 3)
(2, 3, 4)


In [5]:
# Practice
# Creating arrays and predecting their shapes before checking:
import numpy as np

a = np.zeros((5,3)) # Shape = 2D array(matrix) (5,3) of zeros
print(a.shape)
b = np.array([1,2,3,4]) # Shape = 1D array of 4 elements (4,)
print(b.shape)
c = np.ones((2,4,3)) # Shape = 3D array of 2 layers of 4 by 3 matrix (2,4,3)
print(c.shape)
d = np.arange(12) # Shape = 1D array consisting of 12 elements (12,)
print(d.shape)

(5, 3)
(4,)
(2, 4, 3)
(12,)
