In [1]:
import numpy as np
# Create a 1D array of numbers 1-10
v = np.array([1,2,3,4,5,6,7,8,10])
print(v)

[ 1  2  3  4  5  6  7  8 10]


In [3]:
import numpy as np
# Create a 3x3 matrix of zeros
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
# Create a 4x4 identity matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
import numpy as np
# Create an array from 0 to 1 with 11 evenly spaced numbers
space = np.linspace(0,1,11) # start, stop, numpoints
print(space)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [8]:
import numpy as np
# Create a 2x3 array of ones with dtype float32
ones = np.ones((2,3), dtype='float32')
print(ones)
print(ones.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float32
